# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1COPGPp8scUBNovyMpAcOBOk0XxnI9jDh
"""

# -*- coding: utf-8 -*-
import os
import numpy as np
import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.preprocessing.image import img_to_array
import streamlit as st
from PIL import Image
from huggingface_hub import hf_hub_download

# --- PAGE SETUP & UI THEMING ---
st.set_page_config(
    page_title="Gender Classifier - CNN Dashboard",
    page_icon="🧬",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Custom CSS for modern styling
st.markdown("""
    <style>
    .main-header {
        font-size: 2.5rem;
        color: #1E3A8A;
        font-weight: 700;
        margin-bottom: 0.5rem;
    }
    .sub-header {
        font-size: 1.1rem;
        color: #4B5563;
        margin-bottom: 2rem;
    }
    .metric-card {
        background-color: #F3F4F6;
        padding: 15px;
        border-radius: 10px;
        border-left: 5px solid #3B82F6;
        margin-bottom: 10px;
    }
    </style>
""", unsafe_allow_html=True)

# --- PARAMETERS ---
IMG_WIDTH, IMG_HEIGHT = 150, 150
REPO_ID = "Prassh/Male_Female_Image_Classification_using_CNN"

# --- HUGGING FACE MODEL LOADER ---
@st.cache_resource
def load_model_from_hf(repo_id):
    # Try common Keras model filenames from the repository
    possible_filenames = ["model.h5", "binary_image_classifier.h5", "gender_classifier.h5"]

    for filename in possible_filenames:
        try:
            model_path = hf_hub_download(repo_id=repo_id, filename=filename)
            model = tf.keras.models.load_model(model_path)
            return model, filename
        except Exception:
            continue

    # If standard names fail, attempt download assuming a default model.h5
    try:
        model_path = hf_hub_download(repo_id=repo_id, filename="model.h5")
        return tf.keras.models.load_model(model_path), "model.h5"
    except Exception as e:
        st.error(f"Failed to load model from Hugging Face repository '{repo_id}'. Ensure the repository contains a valid `.h5` file.")
        return None, None

# Load the model directly from Hugging Face
with st.spinner("Fetching pre-trained CNN model layers from Hugging Face Hub..."):
    model, deployed_filename = load_model_from_hf(REPO_ID)

# --- SIDEBAR CONTROL PANEL ---
st.sidebar.image("https://img.icons8.com/illustrations/external-fauzidea-flat-fauzidea/128/external-machine-learning-artificial-intelligence-fauzidea-flat-fauzidea.png", width=100)
st.sidebar.title("🎛️ Control Center")
st.sidebar.markdown("Model metadata and source tracking hosted on Hugging Face infrastructure.")

if model:
    st.sidebar.success("✅ Model Loaded Successfully")
    st.sidebar.info(f"**Repo:** `{REPO_ID}`\n\n**File:** `{deployed_filename}`")
else:
    st.sidebar.error("❌ Model Unavailable")
    st.sidebar.title("My Portfolio")

st.sidebar.markdown("""
### 👋 About Me

**Name:** Prashant Gupta

🔗 **LinkedIn:** [Click Here](https://www.linkedin.com/in/prashant-gupta-012320389?utm_source=share_via&utm_content=profile&utm_medium=member_android)

💻 **GitHub:** [Click Here](https://github.com/PrashantGupta8281/AI-ML_Summer_Internship)
""")

# --- MAIN INTERFACE BRANDING ---
st.markdown('<div class="main-header">🧬 CNN Image Classification Dashboard</div>', unsafe_allow_html=True)
st.markdown('<div class="sub-header">An interactive Convolutional Neural Network application designed for Male vs. Female Binary Classification tasks.</div>', unsafe_allow_html=True)

# Organize layout using modern Tabs
tab1, tab2 = st.tabs(["🚀 Image Predictor", "🏋️ Model Trainer & Insights"])

# ==================== TAB 1: PREDICTOR ====================
with tab1:
    st.header("📸 Run Model Predictions")

    uploaded_file = st.file_uploader("Upload an image profile to perform class inference...", type=["jpg", "jpeg", "png"])

    if uploaded_file is not None:
        col1, col2 = st.columns([1, 1])

        with col1:
            st.image(uploaded_file, caption="Uploaded Specimen Image", use_container_width=True)

        with col2:
            st.subheader("🔮 Inference Engine Results")
            with st.spinner("Processing image matrix tensors..."):
                # Load PIL image and prepare target dimensions
                img = Image.open(uploaded_file).convert('RGB')
                img_resized = img.resize((IMG_WIDTH, IMG_HEIGHT))
                x = img_to_array(img_resized)
                x = np.expand_dims(x, axis=0)
                x /= 255.0  # MinMax Scaling normalization

                if model is not None:
                    # Production load & prediction execution from Hugging Face Model
                    predictions = model.predict(x)
                    pred_val = predictions[0][0]
                else:
                    # Fallback validation standard rule logic when model file fails to pull
                    pred_val = np.random.uniform(0.1, 0.9)
                    st.caption("*(Showing calculated mock probabilities since model file could not be loaded)*")

                # Class mapping threshold boundaries
                result_label = "Male" if pred_val >= 0.5 else "Female"
                confidence = pred_val if pred_val >= 0.5 else (1 - pred_val)

                # Output high visibility response metrics
                if result_label == "Male":
                    st.success(f"### Target Classified Class: **{result_label}** ♂️")
                else:
                    st.info(f"### Target Classified Class: **{result_label}** ♀️")

                st.metric(label="Calculated Sigmoid Probability Confidence", value=f"{confidence * 100:.2f}%")
                st.progress(float(confidence))

# ==================== TAB 2: MODEL TRAINER ====================
with tab2:
    st.header("🧠 CNN Topology Architecture & Live Training Execution")

    with st.expander("🔍 Click to inspect network design components"):
        st.code("""
Sequential Model Layers:
1. Conv2D (32 filters, 3x3 kernel, ReLU activation) + MaxPooling2D (2x2)
2. Conv2D (64 filters, 3x3 kernel, ReLU activation) + MaxPooling2D (2x2)
3. Conv2D (128 filters, 3x3 kernel, ReLU activation) + MaxPooling2D (2x2)
4. Flatten (Transitioning Multi-dim Tensors to 1D vector arrays)
5. Dense (128 units, ReLU activation)
6. Dense (1 unit, Sigmoid activation)
        """)

    if model:
        st.subheader("📊 Deployed Network Architecture Summary")
        stringlist = []
        model.summary(print_fn=lambda x: stringlist.append(x))
        short_model_summary = "\n".join(stringlist)
        st.code(short_model_summary)
